byond_host = "play.cm-ss13.com:1400"
comms_key = "69w7aqkndyo1u8ljoldm"
discord_webhook = "https://discord.com/api/webhooks/1427601440247120013/4f-t4gjyJOWUjKgQgc6tjgZBcSm_CVX2H7HcR3M7sLhzMFhYnjMtCL7fZw5W3Z4LZOsM"
response_user_id = "1379066826"
twitch_secret = "r75uBKJXt6SA2xJC5zEjzE0MnMUCc4fCqkOn9WowLVo="